### ISSUE TITLE
Add clojurescript support

### ISSUE THREAD

**Issue by benedekfazekas** [magnars/kaocha-runner.el#1]
thanks @magnars for a package scratching an itch I too have for a while, and thanks @plexus for kaocha.

recently I started migrating our frontend tests (clojurescript units on a project using re-frame) to kaocha. One of our internal requirements is to be able to run the tests from emacs. I've found some blockers here. Maybe I am missing some things and just doing it wrong tho...

- recent cider is quite clever to figure out which REPL to talk to. As our project is clj/cljs/cljc we usually start up both REPLs for development. However kaocha is only available in the clj REPL and when I try to run cljs tests it fails as cider tries to talk to the cljs REPL
- I've found that to able to run cljs tests from the REPL I need to provide test identifiers as 
`(kaocha/run 'cljs:com.foobar.ns/a-test)` as the `cljs:` prefix is not added by `kaocha-runner` so far I was only able to run all tests.

**Comment by benedekfazekas** [comment]
I think I have a solution for the first point, I will do a PR for it.

**Comment by magnars** [comment]
I haven't tried Kaocha with cljs. I've heard it's not quite there yet? I'd be very interested to hear about your setup and how it works. :)

**Comment by plexus** [comment]
CLJS support could still be better (and there are still some improvements coming in the next release), but it works really well for a lot of people.

It should work pretty much exactly like the CLJ version, since it still runs a Clojure (JVM) process for orchestration. As @benedekfazekas points out the main thing is that the test ids for test groups no longer equal the name of the namespace, instead the test id is prefixed with `cljs:`, to disambiguate in case you have the same namespace in clj and cljs (or cljc). 

The [README](https://github.com/lambdaisland/kaocha-cljs/#architecture) has some notes about the architecture, since people are often confused about how kaocha-cljs works exactly.
